Sprint 3
ValeriyaSudarikova/middle.messenger.praktikum.yandex pull request #9
Opened 2023-04-06 18:21 UTC by ValeriyaSudarikova

2023-04-06 18:32 UTC, ValeriyaSudarikova commented
тест падает из-за папки dist, потому что он ее не игнорирует

2023-04-07 08:20 UTC, evgenygil commented on src/controllers/AuthController.ts
> +			const error = document.createElement("span")
Лучше бы наверное вот это завернуть в какую-то отдельную функцию

2023-04-07 08:20 UTC, evgenygil commented on src/index.ts
> +		isProtectedRoute = false
Приватность роутов лучше попробовать убрать прямо в конструкцию use, это будет удобнее в использовании, чем навешивать какую-то логику снаружи потом

2023-04-07 08:20 UTC, evgenygil commented on src/utils/Router.ts
> +class Router {
Удобнее разбить на 2 файла, это 2 разных класса, соответсвенно 2 файла будет нагляднее

2023-04-07 08:20 UTC, evgenygil commented on src/utils/Store.ts
> +window.store = store
А зачем нам внутри `window` стор? Мы же можем пользоваться им просто в приложении, не шаря в общий спейс

2023-05-05 10:08 UTC, evgenygil requested changes
Привет, кажется есть прогресс, много исправлено, но есть еще несколько моментов, на которые нужно обратить внимание, разделил по группам,
Надо поправить:
* При загрузке страницы происходит релоад контента множество раз, если открыть консоль то видно как мигает нода main в HTML дереве, если в это время нажимать на какой-то пункт меню, то ничего не происходит, все сбрасывается
* Нажимаю на кнопку "Активный чат" - ничего не происходит визуально, вижу какой-то ререндер, но в окне пусто
* Нажимаю на иконку сообщения в списке чатов, ничего не происходит (кроме множественного ререндера в дом-дереве), потом второй раз делаю тоже самое, вроде открывается, должно работать с первого раза
* Нет возможности создать чать, или я не нашел, есть строка поиска с соответствующей кнопкой, но сверху заголовок "Новый чат", но например при вводе `test3475235`, открывается чат `test10`, непонятно по какой логике работает поиск

Можно лучше:
* Желательно добавить отправку сообщений по Enter
* При переключении чатов есть некоторая задержка в переключении сообщений, то есть включая чат 2 после чата 1, я где-то на секунду вижу сообщения из чата 1, думаю можно сразу убирать контент, включать например прелоадер, и потом уже новые сообщения

Спасибо, удачи!

2023-05-09 18:03 UTC, ValeriyaSudarikova commented on src/controllers/AuthController.ts
> +		error.classList.add(clas)
тут class - зарезервированное слово, поэтому обычно пишут clas с ошибкой намеренно

2023-05-12 11:52 UTC, evgenygil approved these changes

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
> +	 createMessages(message: Message, users: UserData[]): any {
Тут вполне очевидный ответ, если мы ничего не возвращаем то `void`, если возвращаем, то видимо тип сообщения

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
> +		const cls: "from" | "to" = message.user_id !== myId ? "to" : "from"
Думаю можно `"from" | "to"` отдельно положить в тип

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
> +						newMessage = "";
А зачем нужно хранить newMessage отдельно глобально, это не очень удобно дебажить, может каждая функция может работать с конкретными входящими и выходящими параметрами

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
>  				submit: (event: any) => {
Есть встроенные SyntheticEvent в тайпскрипте

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
> +		if (oldProps.messages && newProps.messages && Object.values(oldProps.messages) !== Object.values(newProps.messages)) {
Это не совсем корректное сравнение между собой, что если например у нас есть 2 объекта одинаковых
```
a = {message: "test2", id: 1}
b = {id: 1, message: "test2"}
```
При таком сравнении через Object.values мы получим false, хотя объекты одинаковые, вообще сравнение массивов не делается просто через ===

2023-05-12 11:52 UTC, evgenygil commented on src/components/chat/chat.ts
> +				this.messages = state.messages[state.selected_chat_data?.chat.id!].sort((a: Message, b: Message) => {
Можно заранее положить в переменную `state.selected_chat_data?.chat.id!` чтобы не брать 2 раза, и причем он не зря ругается, что может не существовать, желательно проверять в таких кейсах

2023-05-12 11:52 UTC, evgenygil commented on src/controllers/ChatController.ts
> +			if (messages) {
Можно в один if - `if (messages && messages[id]) ...`

2023-05-12 11:52 UTC, evgenygil commented on src/controllers/MessageController.ts
> +		const userId = store.getState().user!.data.id;
Много где встречается принудительное указание существования свойства, может быть стоит где-то в типах задать дефолтное значение, например пустой объект, или добавить проверки при инициализации

2023-05-12 11:52 UTC, evgenygil commented on src/controllers/MessageController.ts
> +export default messagesController;
Про дефолтные экспорты писал где-то в одном из множественных ревью, надо стараться избегать их и использовать именованные, если это не какие-то автособираемые структуры в готовых фреймворках

2023-05-12 11:52 UTC, evgenygil commented on src/controllers/AuthController.ts
> +		error.classList.add(clas)
Да, все верно, но никто не пишет заведомо неправильно само слово, скорее пишут `errorClass` или что-то такое

2023-05-12 11:52 UTC, evgenygil commented on src/controllers/UserController.ts
> +			location.reload()
Ну вероятно он не работает как нужно, надо разобраться, нет смысла ни в какой реактивности если мы перезагружаем страницы при любом вызове и получении данных, можно все делать на статических html, всмысле относительно статических без рендера с помощью js

2023-05-12 11:52 UTC, evgenygil commented on .idea/codeStyles/Project 2.xml
Не должно быть папки idea в гите

2023-05-13 14:57 UTC, merged